#!/usr/bin/env bash


frontend_build(){

    for i in "$@" ; do
      case $i in
        "--accounts" )
            echo "building accounts"
            cd packages/accounts
            mkdir build/
          ;;
        "--builder" )
            echo "building builder"
            cd packages/accounts
            mkdir build/
          ;;
      esac
   done
}